#!/bin/sh

function usage {
  cat <<EOM
Usage: $(basename "$0") [option] [string] [regexp] [file]

Option:
  -h          Display help
  -a          Add [string] at the begining of the line
  -A          Add [string] at the end of the line
  -d          Delete [string] at the begining of the line
  -D          Delete [string] at the end of the line

Note:
  If you use special characters in the [string], escape them.

  e.g.)
    If you add or delete #, pass \# for \$2.
    If you add or delete ;, pass \; for \$2.
    If you add or delete //, pass \\\/\\\/ for \$2.
    If you add or delete <!--, pass \<\!\\-\\- for \$2.
    If you add or delete -->, pass \\\-\\-\> for \$2.
EOM

  exit 2
}

if [ "$1" = "-h" ]; then
  usage
elif [ $# -lt 4 ]; then
  echo Error: Not enough arguments. Check the usage below.
  echo
  usage
fi

while getopts ":aAdDh" optKey; do
  case "$optKey" in
    a)
      # Format: s/.*[regexp]/[string]&/
      REGEXP=s\/.*$3\/$2\&\/
      ;;
    A)
      # s/[regexp].*/&[string]/
      REGEXP=s\/$3.*\/\&$2\/
      ;;
    d)
      # /^[string].*[regexp]/s/^[string]//;
      REGEXP=/^$2.*$3/s\/^$2\/\/\;
      ;;
    D)
      # /[regexp].*[string]$/s/[string]$//;
      REGEXP=/$3.*$2$/s\/$2$\/\/\;
      ;;
    *)
      echo Error: An unsupported option was passed. Check the usage below.
      usage
      ;;
  esac
done

sed -i.bak "$REGEXP" $4 &&
echo Backup file \"$4.bak\" was created next to \"$4\"
